# Uncomment this line to define a global platform for your #project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'TheSpartanDrive' do

source 'https://github.com/CocoaPods/Specs.git'
pod 'FileBrowser', '~> 0.1'

end

